### ISSUE TITLE
LiveSharp parses on save when not debugging

### ISSUE THREAD

**Issue by VincentH-Net** [OYIon/LiveSharp#10]
VSIX 1.0.21, NuGet 1.0.16
Page contains:
```C#
        void List_ItemSelected(object sender, SelectedItemChangedEventArgs e)
        {
            var dialogueSummary = e.SelectedItem as DialogueSummary;
            ((ListView)sender).SelectedItem = null; // Prevent item selection
            if (dialogueSummary != null && dialogueSummary.Id != Guid.Empty) ViewModel.ContinueToDialogueCommand.Execute(dialogueSummary);
        }
```
On each save, when not debugging, even after close and open VS, a popup is shown with below text.

L# should only parse the page on save while debugging.

---------------------------

---------------------------
List_ItemSelected LiveProjectCommon.ETSerializationException: Serialization failed for: 

DialogueSummary ---> System.Exception: Exception of type 'System.Exception' was thrown.

   at LiveProjectCommon.ExpressionTreeBuilder.GetIdentifierExpression(IdentifierNameSyntax ins) in C:\Projects\LiveSharp\src\LiveSharp.VisualStudio\Services\ExpressionTreeBuilder.cs:line 1617

   at LiveProjectCommon.ExpressionTreeBuilder.Convert(SyntaxNode node, XElement initializerType) in C:\Projects\LiveSharp\src\LiveSharp.VisualStudio\Services\ExpressionTreeBuilder.cs:line 555

   --- End of inner exception stack trace ---

   at LiveProjectCommon.ExpressionTreeBuilder.Convert(SyntaxNode node, XElement initializerType) in C:\Projects\LiveSharp\src\LiveSharp.VisualStudio\Services\ExpressionTreeBuilder.cs:line 1257

   at LiveProjectCommon.ExpressionTreeBuilder.Convert(SyntaxNode node, XElement initializerType) in C:\Projects\LiveSharp\src\LiveSharp.VisualStudio\Services\ExpressionTreeBuilder.cs:line 1255

   at LiveProjectCommon.ExpressionTreeBuilder.Convert(SyntaxNode node, XElement initializerType) in C:\Projects\LiveSharp\src\LiveSharp.VisualStudio\Services\ExpressionTreeBuilder.cs:line 1255

   at LiveProjectCommon.ExpressionTreeBuilder.<>c__DisplayClass16_0.<SerializeVariableDeclarationSyntax>b__0(VariableDeclaratorSyntax v) in C:\Projects\LiveSharp\src\LiveSharp.VisualStudio\Services\ExpressionTreeBuilder.cs:line 1380

   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()

   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()

   at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)

   at System.Xml.Linq.XElement..ctor(XName name, Object content)

   at LiveProjectCommon.ExpressionTreeBuilder.Convert(SyntaxNode node, XElement initializerType) in C:\Projects\LiveSharp\src\LiveSharp.VisualStudio\Services\ExpressionTreeBuilder.cs:line 1255

   at LiveProjectCommon.ExpressionTreeBuilder.GetExpressionTree() in C:\Projects\LiveSharp\src\LiveSharp.VisualStudio\Services\ExpressionTreeBuilder.cs:line 31

   at LiveSharp.VisualStudio.Services.RuntimeCodeService.<PrepareUpdatesAsync>d__13.MoveNext() in C:\Projects\LiveSharp\src\LiveSharp.VisualStudio\Services\RuntimeCodeService.cs:line 112
---------------------------
OK   
---------------------------

**Comment by ionoy** [comment]
should be fixed in 1.0.25
