### ISSUE TITLE
SYNTAX: creating array gives exception

### ISSUE THREAD

**Issue by VincentH-Net** [OYIon/LiveSharp#28]
When the Page Build method contains creating an array, e.g.:

`var entries = new Entry[2];`

Then on save LiveSharp gives an exception:

> LiveSharp.VisualStudio.Serialization.ETSerializationException: Serialization failed for: 
new Entry[2]
Block --> {...
 EqualsValueClause --> = new Entry[2]
  ArrayCreationExpression --> new Entry[2] ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at LiveSharp.VisualStudio.Serialization.ExpressionTreeBuilder.ArrayCreationExpression(ArrayCreationExpressionSyntax arrayCreationExpression, ConversionContext conversionContext) in c:\Projects\LiveSharp\src\LiveSharp.VisualStudio\Serialization\ExpressionTreeBuilder.Handlers.cs:line 687
   at LiveSharp.VisualStudio.Serialization.ExpressionTreeBuilder.<>c__DisplayClass12_0`1.<MakeHandler>b__0(SyntaxNode node, ConversionContext ctx) in c:\Projects\LiveSharp\src\LiveSharp.VisualStudio\Serialization\ExpressionTreeBuilder.cs:line 196
   at LiveSharp.VisualStudio.Serialization.ExpressionTreeBuilder.Convert(SyntaxNode node, ConversionContext context) in c:\Projects\LiveSharp\src\LiveSharp.VisualStudio\Serialization\ExpressionTreeBuilder.cs:line 165
   --- End of inner exception stack trace ---
   at LiveSharp.VisualStudio.Serialization.ExpressionTreeBuilder.Convert(SyntaxNode node, ConversionContext context) in c:\Projects\LiveSharp\src\LiveSharp.VisualStudio\Serialization\ExpressionTreeBuilder.cs:line 175
   at LiveSharp.VisualStudio.Serialization.ExpressionTreeBuilder.EqualsValueClause(EqualsValueClauseSyntax equalsValueClauseSyntax, ConversionContext conversionContext) in c:\Projects\LiveSharp\src\LiveSharp.VisualStudio\Serialization\ExpressionTreeBuilder.Handlers.cs:line 475
   at LiveSharp.VisualStudio.Serialization.ExpressionTreeBuilder.<>c__DisplayClass12_0`1.<MakeHandler>b__0(SyntaxNode node, ConversionContext ctx) in c:\Projects\LiveSharp\src\LiveSharp.VisualStudio\Serialization\ExpressionTreeBuilder.cs:line 196
   at LiveSharp.VisualStudio.Serialization.ExpressionTreeBuilder.Convert(SyntaxNode node, ConversionContext context) in c:\Projects\LiveSharp\src\LiveSharp.VisualStudio\Serialization\ExpressionTreeBuilder.cs:line 169
   at LiveSharp.VisualStudio.Serialization.ExpressionTreeBuilder.SerializeVariableDeclarationSyntax(VariableDeclarationSyntax vd, List`1& parameters, ConversionContext conversionContext) in c:\Projects\LiveSharp\src\LiveSharp.VisualStudio\Serialization\ExpressionTreeBuilder.Helpers.cs:line 39
   at LiveSharp.VisualStudio.Serialization.ExpressionTreeBuilder.Block(BlockSyntax blockSyntax, ConversionContext conversionContext) in c:\Projects\LiveSharp\src\LiveSharp.VisualStudio\Serialization\ExpressionTreeBuilder.Handlers.cs:line 384
   at LiveSharp.VisualStudio.Serialization.ExpressionTreeBuilder.<>c__DisplayClass12_0`1.<MakeHandler>b__0(SyntaxNode node, ConversionContext ctx) in c:\Projects\LiveSharp\src\LiveSharp.VisualStudio\Serialization\ExpressionTreeBuilder.cs:line 196
   at LiveSharp.VisualStudio.Serialization.ExpressionTreeBuilder.Convert(SyntaxNode node, ConversionContext context) in c:\Projects\LiveSharp\src\LiveSharp.VisualStudio\Serialization\ExpressionTreeBuilder.cs:line 169
   at LiveSharp.VisualStudio.Serialization.ExpressionTreeBuilder.GetSerializedMethodBody() in c:\Projects\LiveSharp\src\LiveSharp.VisualStudio\Serialization\ExpressionTreeBuilder.cs:line 149
   at LiveSharp.VisualStudio.Services.RuntimeCodeService.<PrepareUpdatesAsync>d__10.MoveNext() in c:\Projects\LiveSharp\src\LiveSharp.VisualStudio\Services\RuntimeCodeService.cs:line 82

**Comment by ionoy** [comment]
fixed in the next release
