### ISSUE TITLE
Not implemented exception on Tizen.net watch app

### ISSUE THREAD

**Issue by EmilAlipiev** [OYIon/LiveSharp#43]
have you tested it on a Tizen.net or tizen forms app? It throws exception as not implemented exception.  It supposed to be similar to xamarin.forms but somehow not working

**Comment by ionoy** [comment]
Not yet. Can you post the exception details?

**Comment by EmilAlipiev** [comment]
Something is changed in the new 1.1.20 version but still not working on Tizen watch. Here is the log 

```
13:05:11 Error: failed to start workspace process
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeLoadException: Method 'GetMethod' in type 'LiveSharp.Services.InjectedMethodsService' from assembly 'LiveSharp.Workspace, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at LiveSharp.LiveSharpWorkspace..ctor(ILogger logger, IEventBus eventBus, Action`3 broadcastSender)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at LiveSharp.ServerApp.Services.ServerService.StartWorkspace(String nuGetPackagePath, String solutionPath, String projectDir, String projectName) in /Users/runner/runners/2.160.1/work/1/s/src/LiveSharp.ServerApp/Services/ServerService.cs:line 194

```

**Comment by ionoy** [comment]
Did you update LiveSharp Server to the latest version?
