### ISSUE TITLE
PlatformNotSupportedException for webapp project on macos

### ISSUE THREAD

**Issue by thisisthekap** [OYIon/LiveSharp#47]
## Environment

|Property|Value|
|-|-|
|OS|mac OS Catalina 10.15.2|
|IDE|Rider JetBrains Rider 2019.3.1|
|dotnet core version|3.1.101|

## Steps to reproduce

1. Create project using `dotnet new webapp`
2. Add LiveSharp to this project
3. Run the project

## Reproduction

Reproduction can be found at https://github.com/thisisthekap/livesharp-notsupported-bug

## Stacktrace

```
System.PlatformNotSupportedException: Socket.IOControl handles Windows-specific control codes and is not supported on this platform.
  at at System.Net.Sockets.SocketPal.WindowsIoctl(SafeSocketHandle handle, Int32 ioControlCode, Byte[] optionInValue, Byte[] optionOutValue, Int32& optionLength)
  at at System.Net.Sockets.Socket.IOControl(Int32 ioControlCode, Byte[] optionInValue, Byte[] optionOutValue)
  at at System.Net.Sockets.Socket.IOControl(IOControlCode ioControlCode, Byte[] optionInValue, Byte[] optionOutValue)
  at at LiveSharp.ServerClient.LiveServerClient.SetSocketKeepAliveValues(UInt64 time, UInt64 interval)
  at at LiveSharp.ServerClient.LiveServerClient..ctor(String host, IReadOnlyList`1 portRange, ILogger logger, Action`1 onMessageReceived)
  at at LiveSharp.Runtime.LiveSharpRuntime.Start(String ip, String solutionPath, String projectName, String projectDir, String nuGetPackagePath, Type liveXamlPluginType, Type inspectorType, Type updateHandlerType)
  at test.webapp.Program.Main(String[] args) in /Users/ckapplmueller/repos/livesharp-notsupported-bug/test.webapp/Program.cs:15
```

**Comment by ionoy** [comment]
fixed in 1.1.25
