### ISSUE TITLE
"An element with the same name ... already exists in the NameScope"

### ISSUE THREAD

**Issue by GiampaoloGabba** [OYIon/LiveSharp#53]
Hello,
everytime i try update a Xaml page containing a view with `x:Name` , i get this error:

![image](https://user-images.githubusercontent.com/8319337/74269334-9a7ab980-4d09-11ea-8779-8606477d9251.png)

Xaml Example:

```
<StackLayout Spacing="20" Padding="20">

        <WebView x:Name="WebViewTesti" BackgroundColor="White" VerticalOptions="FillAndExpand" />

    </StackLayout>
```

**Comment by ionoy** [comment]
Hey Giampaolo, thanks for the feedback!

Unfortunately, I can't reproduce it in my sample project. Would it be possible for you to create a reproduction?

**Comment by ionoy** [comment]
Oh, wait. Actually I do see it, just not on the emulator screen. Only in the Output console. I will check it out and get back to you.

**Comment by ionoy** [comment]
Actually, this was another warning message that I have encountered. Can you please check the Output for any suspicious messages when you perform the update?

Thanks!

**Comment by ionoy** [comment]
Can you check the 1.1.37? I think it should fix your issue.

Thanks!

**Comment by lhughey** [comment]
The error details i'm seeing in Visual studio are:

`System.IO.FileLoadException: Assembly with same name is already loaded
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at LiveSharp.ServerApp.Services.ServerService.StartWorkspace(String nuGetPackagePath, String solutionPath, String projectDir, String projectName) in /Users/runner/runners/2.163.1/work/1/s/src/LiveSharp.ServerApp/Services/ServerService.cs:line 195`

**Comment by lhughey** [comment]
I tried to post via Gitter, but they are down right now. v37 is erroring out at startup. https://imgur.com/a/gz4wLyR

**Comment by Huaba93** [comment]
> Can you check the 1.1.37? I think it should fix your issue.
> 
> Thanks!

I had the same issue, works now
