### ISSUE TITLE
LiveSharp looking for assemblies on not wrong sdk

### ISSUE THREAD

**Issue by nukedbit** [OYIon/LiveSharp#57]
Hi i was just trying livesharp with blazor.
i get this error on the livesharp server log console

`System.IO.FileNotFoundException: Could not load file or assembly 'C:\Program Files\dotnet\sdk\3.1.102\Sdks\Microsoft.NET.Sdk.Razor\extensions\mvc-3-0\Microsoft.AspNetCore.Mvc.Razor.Extensions.dll'. Impossibile trovare il percorso specificato.
File name: 'C:\Program Files\dotnet\sdk\3.1.102\Sdks\Microsoft.NET.Sdk.Razor\extensions\mvc-3-0\Microsoft.AspNetCore.Mvc.Razor.Extensions.dll'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at LiveSharp.RazorHandler..ctor(Project project, ILogger logger)
   at LiveSharp.LiveSharpWorkspace.LoadSolution(String nugetPath, String solutionPath, String projectDir, String projectName, Boolean needWatcherSubscribe)
`
it is looking for a 3.1.102 sdk but i have only the 3.1.200 installed.

Let me know if you need more info

**Comment by ionoy** [comment]
Hello @nukedbit 

I have uploaded the update that should fix this issue https://www.nuget.org/packages/LiveSharp/1.1.56

Please see if it works.

Thanks!

**Comment by nukedbit** [comment]
Thanks it's working now on the main project, can i make it detect changes on libraries?

**Comment by ionoy** [comment]
I have fixed the multiple project support it the attached NuGet package. Please if it works for you.

Thanks!
 
[LiveSharp.1.1.57.zip](https://github.com/OYIon/LiveSharp/files/4385664/LiveSharp.1.1.57.zip)

**Comment by nukedbit** [comment]
Hi thanks, it's not working on my projects. One thing i have noticed i don't know if it could be related.
my razor class libraries are netcoreapp3.1 not netstandard.
But i have also tried with a netstandard one and dosent work.
i also have tried to modify a razor components loaded from a class library in a completely new project and it dosent work.
I have attached my sample project for reference

[WebApplication.zip](https://github.com/OYIon/LiveSharp/files/4386353/WebApplication.zip)

**Comment by ionoy** [comment]
I forgot to mention. You need to install LiveSharp to other class libraries if you want to update them in runtime.

Secondly, for some reason, external components don't update, but external pages do. I will investigate it further and let you know when there is an update.

**Comment by ionoy** [comment]
I have published an update to the public NuGet feed. Can you check if it fixes your issues?

**Comment by nukedbit** [comment]
Wonderful! now it works on most component i have a few that crash after a change.
Probably some broken state after the change. If i find a way to reproduce it i will send a sample.

` Unhandled exception rendering component: Exception has been thrown by the target of an invocation.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure , RenderTreeBuilder )
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at LiveSharp.Runtime.LiveSharpRuntime.ExecuteVoid(Object methodBody, Object thisInstance, Int32 argCount, Object arg0, Object arg1, Object arg2, Object arg3, Object arg4, Ob
ject arg5, Object arg6, Object arg7, Object arg8, Object arg9, Object arg10, Object arg11)
   at StackX.Site.Pages.Users.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit '4QzpQzPQLjNtQBjexu7snX-6xc4OYBAaN4GDSY6vLUg'.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure , RenderTreeBuilder )
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at LiveSharp.Runtime.LiveSharpRuntime.ExecuteVoid(Object methodBody, Object thisInstance, Int32 argCount, Object arg0, Object arg1, Object arg2, Object arg3, Object arg4, Ob
ject arg5, Object arg6, Object arg7, Object arg8, Object arg9, Object arg10, Object arg11)
   at StackX.Site.Pages.Users.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Exception has been thrown by the target of an invocation.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure , RenderTreeBuilder )
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at LiveSharp.Runtime.LiveSharpRuntime.ExecuteVoid(Object methodBody, Object thisInstance, Int32 argCount, Object arg0, Object arg1, Object arg2, Object arg3, Object arg4, Ob
ject arg5, Object arg6, Object arg7, Object arg8, Object arg9, Object arg10, Object arg11)
   at StackX.Site.Pages.Users.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'LkZonsN6Z1wpWe-f8Ubf0HVOGYMPoU5sbOfjpYpqV8Q'.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure , RenderTreeBuilder )
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at LiveSharp.Runtime.LiveSharpRuntime.ExecuteVoid(Object methodBody, Object thisInstance, Int32 argCount, Object arg0, Object arg1, Object arg2, Object arg3, Object arg4, Ob
ject arg5, Object arg6, Object arg7, Object arg8, Object arg9, Object arg10, Object arg11)
   at StackX.Site.Pages.Users.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
`
