### ISSUE TITLE
Error on startup 

### ISSUE THREAD

**Issue by MBrekhof** [OYIon/LiveSharp#61]
Xamarin Forms 4.5

10:53:45 watcher created for at /Users/n0515405/src/MBJ-BJong/source/app/AapForms/AapForms/
10:53:45 Starting job: Dry run for BJong
10:53:45 Ended job: Dry run for BJong (62)
10:53:58 Error: EndReceive failed
System.Xml.XmlException: Name cannot begin with the ' ' character, hexadecimal value 0x20. Line 68, position 81.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ParseQName(Boolean isQName, Int32 startOffset, Int32& colonPos)
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
   at LiveSharp.ServerApp.Screens.InspectorScreen.ServerService_InspectorPacketReceived(Byte contentType, String message) in /Users/runner/runners/2.163.1/work/1/s/src/LiveSharp.ServerApp/Screens/Inspector/InspectorScreen.cs:line 44
   at LiveProjectCommon.Server.LiveServer.MessageReceived(ServerMessage message, Client socket) in /Users/runner/runners/2.163.1/work/1/s/src/LiveSharp.ServerApp/Network/LiveServer.cs:line 88
   at LiveSharp.ServerClient.MessageParser.Feed(Byte b) in /Users/runner/runners/2.163.1/work/1/s/src/LiveSharp.ServerClient/MessageParser.cs:line 111
   at LiveSharp.ServerClient.ParserBase`1.Feed(Byte[] buffer, Int32 bytesRead) in /Users/runner/runners/2.163.1/work/1/s/src/Sources/ParserBase.cs:line 20
   at LiveProjectCommon.Server.LiveHost.EndReceive(IAsyncResult ar) in /Users/runner/runners/2.163.1/work/1/s/src/LiveSharp.ServerApp/Network/LiveHost.cs:line 101
10:53:58 client disconnected: 192.168.178.29:63039

**Comment by ionoy** [comment]
Hey @MBrekhof 

Thanks for the feedback. Sorry, I haven't been able to answer earlier. There is a beta version of the new LiveSharp, which should mitigate this and many other issues. Here are the links:

Server: https://github.com/OYIon/LiveSharp/releases/tag/1.5-beta
NuGet: https://www.nuget.org/packages/LiveSharp/ (make sure to install prerelease version)

Thanks,
Mihhail
