### ISSUE TITLE
'AssemblyTimestamp' was not present in the dictionary

### ISSUE THREAD

**Issue by neo210211** [OYIon/LiveSharp#73]
Hi! I am on the latest version of LiveSharp NuGet v1.5.23 and latest version of the Server App v.1.5.1 for Windows. I am seeing the following error in the Server log. Please help.
```
14:44:56 Error: Compilation failed:
System.Collections.Generic.KeyNotFoundException: The given key 'AssemblyTimestamp' was not present in the dictionary.
at System.Collections.Generic.Dictionary2.get_Item(TKey key) at LiveSharp.Infrastructure.WorkspaceLoader.GetProjectInfo(String solutionCacheDir, String projectName, Dictionary2 properties)
at LiveSharp.Infrastructure.WorkspaceLoader.GetProjectInfo(String solutionCacheDir, String projectName, String[] projectInfoLines)
at LiveSharp.Infrastructure.WorkspaceLoader.GetWorkspace(String nugetPath, String solutionPath)
at LiveSharp.LiveSharpWorkspace.LoadSolution(String nugetPath, String solutionPath, String projectDir, String projectName, Boolean needWatcherSubscribe)
```

**Comment by ionoy** [comment]
@neo210211 did you try restarting Visual Studio / Rider? This seems like the LiveSharp MSBuild task mismatch.

**Comment by neo210211** [comment]
I did. It didn't help.

**Comment by ionoy** [comment]
Do you have LiveSharp installed in multiple projects?

**Comment by neo210211** [comment]
Just one project.

After a restart of VS and rebuild, the error no longer appears. However, I am not able to HotReload. Please help.

**Comment by ionoy** [comment]
Do you see Dashboard starting when your application starts? Do you have the latest NuGet package installed? Also, there might be useful info in the logs at `%TEMP%\LiveSharp\server-*.log`

**Comment by neo210211** [comment]
On the Dashboard:

```
Title "Messages"

AppTheme xxx.Models.AppTheme

Changing System.Reactive.Linq.ObservableImpl.Cast`2[System.Object,ReactiveUI.IReactivePropertyChangedEventArgs`1[ReactiveUI.IReactiveObject]]

Changed System.Reactive.Linq.ObservableImpl.Cast`2[System.Object,ReactiveUI.IReactivePropertyChangedEventArgs`1[ReactiveUI.IReactiveObject]]

ThrownExceptions ReactiveUI.ScheduledSubject`1[System.Exception]
```

**Comment by ionoy** [comment]
Do you see anything in the Output window when you update the file?

**Comment by neo210211** [comment]
Nope.

The error on Dashboard appears when my mobile app is launched.

**Comment by JohnCampionJr** [comment]
I'm having the same exact problem.  Plain, starter project.  Same error and symptoms as this issue.

**Comment by ionoy** [comment]
I have published NuGet package 1.5.27, which should fix the issue.

**Comment by neo210211** [comment]
I just checked. The latest is 1.5.25. I will check again later for 1.5.27.

**Comment by ionoy** [comment]
It was probably still publishing. Should be listed now.

**Comment by neo210211** [comment]
Just updated NuGet to 1.5.27 and I am using Server App v.1.5.1 for Windows.

After restarting Visual Studio and rebuilding my mobile app after a _Clean_, I can no longer connect to your Server App -- while Visual Studio output says "LiveSharp Server connected". Please help.

```
Loaded assembly: /private/var/containers/Bundle/Application/2BD99E55-7EDE-4B8A-8AD5-3D8E43FB223C/QunFa.iOS.app/LiveXaml.Standard.dll [External]
[0:] livesharp: Transport type: LiveSharp.ServerClient.SocketTransport
[0:] livesharp: Connecting to 192.168.68.129:50540
[0:] livesharp: Activating UpdateHandler XamarinFormsUpdateHandler
[0:] livesharp: Activating UpdateHandler XamarinFormsViewHandler
[0:] livesharp: Activating UpdateHandler XamarinFormsViewModelHandler
Thread started: <Thread Pool> #14
Thread started:  #15
Loaded assembly: /private/var/containers/Bundle/Application/2BD99E55-7EDE-4B8A-8AD5-3D8E43FB223C/QunFa.iOS.app/System.Text.RegularExpressions.dll [External]
Thread started:  #16
[0:] livesharp: Connected to 192.168.68.129:50540
[0:] livesharp: LiveSharp Server connected
```
